service: nexspro

image: your-name/nexspro

servers:
  web:
    hosts:
      - 192.168.0.1

proxy:
  ssl: true
  host: nexspro.your-domain.com

registry:
  username: your-dockerhub-user
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

builder:
  arch: amd64
  args:
    RUBY_VERSION: 3.4.2

# Optional: shared volumes (ActiveStorage)
volumes:
  - "nexspro_storage:/rails/storage"

# Optional: run Redis or DB locally
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306

# Optional aliases
# aliases:
#   console: app exec -- bin/rails console
#   logs: app logs -f
